name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

    - name: Run tests
      run: mvn test

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
          name: Test-Reports
          path: target/reports


